name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: twes
    env:
      NAME_IMAGE_PROJECT: teste
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # build image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME$NAME_IMAGE_PROJECT .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME$NAME_IMAGE_PROJECT

      # deploy image
      - name: Deploy Docker image
        run: gcloud run deploy site --image $IMAGE_NAME$NAME_IMAGE_PROJECT --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 80 --allow-unauthenticated
